### ISSUE TITLE
BUG: get_spec_handler fails where retrive does not

### ISSUE THREAD

**Issue by CJ-Wright** [NSLS-II/filestore#112]
Here is my error, I was trying to find the spec of the data I was taking so I could find its path to use pyFAI on it.
Thoughts?
https://gist.github.com/CJ-Wright/bfaff6b5feae6325d5abd3ecae75a3e0

**Comment by tacaswell** [comment]
Do not do that.

The reason is that the uid in the events is a datum uid, `get_spec_handler` expects a resource uid.

You probably want the handlers in https://github.com/NSLS-II/filestore/blob/master/filestore/path_only_handlers.py

Can't you throw arrays at pyfai?

**Comment by CJ-Wright** [comment]
No pyFAI calib wants files. I don't have an in-python version running
