### ISSUE TITLE
MTN: split mongo filestore from everything else

### ISSUE THREAD

**Issue by CJ-Wright** [NSLS-II/filestore#123]
It seems some of the core functionality of filestore doesn't depend on mongo and is shared with portable-fs. It might be nice to cleave these from filestore and put them where both fs and portable-fs can access them. Another possibility is to merge portable-fs with fs and just have them as different backends, with the default going to mongo.

**Comment by danielballan** [comment]
Ha, I didn't even see this issue until now, but we are clearly on the same wavelength: https://github.com/NSLS-II/metadatastore/issues/259

**Comment by danielballan** [comment]
This is partly done / underway in databroker.
