### ISSUE TITLE
Move `resource_given_eid` to `FileStoreRO`

### ISSUE THREAD

**Issue by CJ-Wright** [NSLS-II/filestore#125]
Currently this is in [FileStore](https://github.com/NSLS-II/filestore/blob/master/filestore/fs.py#L594) but for `db.export()` to work it also needs to be in `FileStoreRO`.

**Comment by danielballan** [comment]
Could you open a PR to do this? While you're at it, you might want to make sure all the methods used by export are available on FileStoreRo.

**Comment by CJ-Wright** [comment]
Yes but after Tues next week, finals :(
