### ISSUE TITLE
MTN: codecov?

### ISSUE THREAD

**Issue by CJ-Wright** [NSLS-II/filestore#127]
Do we want codecov integration?

**Comment by tacaswell** [comment]
eh, the mid-term fate of the mds / fs / protabale* repo organization is still a bit up in the air.  Unless you feel a burning desire to do this _now_ I would not worry about it.

**Comment by CJ-Wright** [comment]
It just felt weird not having more than one Github check.

**Comment by danielballan** [comment]
Done as part of octomerge.
