### ISSUE TITLE
ENH: Dev Class

### ISSUE THREAD

**Issue by CJ-Wright** [NSLS-II/filestore#130]
Would it be possible to have a `FSDev` class?
This way we can actually inspect the database and have all the scary tools?
I am having a lot of trouble checking that I have a valid `FS` and poking the database directly, eg getting back all the datums, searching the database, even just enumerating the number of records, etc might be good.

In discussion with @danielballan

**Comment by danielballan** [comment]
Track https://github.com/NSLS-II/databroker/issues/186
