### ISSUE TITLE
extra index in image?

### ISSUE THREAD

**Issue by ordirules** [NSLS-II/filestore#131]
Not sure if it's just me, but I think filestore is creating an extra index. I could be wrong:
I run this code:
```python
imgs = chxdb.get_images(hdr, 'eiger4m_single_image')
```
The handler (from CHX) is:
```python 
chxdb.fs.register_handler('AD_EIGER2', EigerHandler2)
```
```python 

class EigerHandler2:
#omitted text....
    def __call__(self, seq_id):
# omitted text
        return EigerImages2(master_path, self._images_per_file, md=md)
```

to access, I need to run `imgs[0][0]` instead of `imgs[0]`.

However, if I just run 
```python
imgs = EigerImages2(somefilename)
```
then `imgs[0]` yields my image.

Any thoughts? I've sort of poked around but haven't seen anything yet. Peraps you have some insight (and perhaps I've used filestore wrong).

thanks!

I am using version : 0.6.0+10.g7e11f8a

**Comment by ordirules** [comment]
@yugangzhang you may be interested in this, I think you must be experiencing same issue.

**Comment by danielballan** [comment]
To summarize what we talked about on Slack here for future reference by others:

The *handler* is returning data from multiple Events, and the first axis is counting those Events. The *PIMS reader* targets one file (corresponding to one Event) and so it has one less dimension.
