### ISSUE TITLE
Suggestion: insert_resource should not treat filename differently from other kwargs

### ISSUE THREAD

**Issue by danielballan** [NSLS-II/filestore#23]
Current API:

    insert_resource('spec-alias', filename, {snowflake_argument=whatever})

Proposed API:

    insert_resource('spec-alias', filename, snowflake_argument=whatever)

Examples illustrating why this is nice:

* when you need more than a filename to specify where the data is

        insert_resource('hdf5-slice-into-single-dataset', filename='example.h5', dataset_name='dataset-name')

* when there is no filename at all

        insert_resource('weather-forecast', time=time, latitude=latitude, longitude=longitude)
        # data from 'https://api.forecast.io/forecast/APIKEY/LATITUDE,LONGITUDE,TIME'

**Comment by danielballan** [comment]
@stuwilkins Obviously this would break your code so it needs your approval.

**Comment by tacaswell** [comment]
Closing as per discussion in person.

 - it is good to force at least one argument and all physical resources should have a path
 - if it is not needed, then pass `None` to make the point that the resource is probably non-physical
