### ISSUE TITLE
HXN detector 

### ISSUE THREAD

**Issue by licode** [NSLS-II/filestore#38]
HXN is using Quantum Xspress3 detectors. Here is the related module https://github.com/newville/xspress3/.

But we still need to write a h5 handler within filestore.

**Comment by tacaswell** [comment]
A version of this exists in hxn tools should it be moved upstream @klauer ?

**Comment by klauer** [comment]
Short answer:
We can move it upstream eventually, but for the moment let's leave it in `hxntools`.

Long answer:
For those that may be confused as to what this is all about: @licode posted the EPICS IOC for the Xspress3 fluorescence detector readout. I wrote a basic xspress3 areaDetector filestore SignalDetector based on @stuwilkins's implementation (for step scanning), an areaDetector configuration instance based on my old areaDetector configuration classes (for setting up step/fly scans), and an hdf5 handler (for handling acquired data from both step/fly-scans), all of which are in `hxntools.detectors` as @tacaswell mentioned. On second thought, that probably didn't clear up much.

In any case, breaking up all parts of this and putting them into the "proper" places in ophyd/filestore/etc. is more effort than it's worth currently for a detector only in use at the HXN. I'll make an attempt to finalize it on the HXN side before we move forward - and hopefully I'll be back by next week to continue on it.

**Comment by danielballan** [comment]
😢
