### ISSUE TITLE
Split repo into filestore and filestore_handlers

### ISSUE THREAD

**Issue by danielballan** [NSLS-II/filestore#54]
This point is to isolate dependencies. We might release filestore_handlers much more frequently than core filestore. I have now-stale branch that does this.

**Comment by CJ-Wright** [comment]
This would be good

**Comment by danielballan** [comment]
Current thinking among @tacaswell, @stuartcampbell, and myself (per an in-person conversation awhile back that I hope I'm recalling accurately) is that databroker is better off as a one-stop-shop. We can still isolate heavy dependencies by module and take advantage of pip's partial-package installation feature, which did not exist (to my knowledge) when I opened this issue.
