### ISSUE TITLE
do something about cached file-globbed handler

### ISSUE THREAD

**Issue by tacaswell** [NSLS-II/filestore#65]
If you construct the handler to a tiff sequence handler before all of the files are written to disk then the file glob in pims will only see the frames that are _currently_ written to disk.  Future attempts to access the the handler will never see the additional frames (as the handler object is cached).

The solution is probably for the handlers like this to on access out of range refresh their underlying pims object before raising.

**Comment by sghose** [comment]
Thanks Tom. Will wait to test tis on Tuesday. Good Luck for the presentation.
