### ISSUE TITLE
image arrays from databroker have no data at XPD beamline

### ISSUE THREAD

**Issue by sghose** [NSLS-II/filestore#67]
The image arrays that are returned from
```
get_images(db[-1], 'pe1_image_lightfield')
```
on the xf28id1-ws2 beamline computer are of `uint8` type and have only two values 0 and 255.  The tiff file in the storage backend directory looks OK and has X-ray image.  Please correct the tiff reading functions to fix this data loss.

@pavoljuhas, @danielballan, @timoHMM

**Comment by danielballan** [comment]
Let's not throw around the word "data loss" in this case, @sghose. Nothing is being or has been lost.

In a phone conversation with @pavoljuhas and @timoHMM we established that the TIFFs are being saved properly. But, in the analysis stage, they not being correctly read in as numpy arrays.

@timoHMM later reported that they are able to read their images through jupyterhub. It's just not working the `collection` conda env at the beamline workstation.

Both environments are running the same versions of tifffile (0.3.1), pims (0.2.2-138-gc98edfc), and PIL (1.1.7) so I am stumped for now.

**Comment by danielballan** [comment]
Note to selves:

jupyterhub (xf28id-ca1) analysis env: filestore is at '0.2.0+0.gee58b93.dirty' 
beamline workstation (xf28id1-ws2) collection env: filestore is at '0.2.1+0.gfdc4740.dirty'

**Comment by danielballan** [comment]
Note different data types. Still unclear which code is responsible for the change.

xf28id1-ws2:
```
In [19]: get_images(db['4e1af641'], 'pe1_image_lightfield')[0].dtype
Out[19]: dtype('uint8')
```

xf28id-ca1:
```
In [28]: get_images(db['4e1af641'], 'pe1_image_lightfield')[0].dtype
Out[28]: dtype('float32')
```

**Comment by danielballan** [comment]
Both machines have the same tifffile, libtiff:

```
$ conda list | grep tiff
libtiff                   4.0.2                         1  
tifffile                  0.3.1                  nppy34_0  
```

**Comment by danielballan** [comment]
@pavoljuhas Mystery solved: based on profiling (`%prun` magic) I can see that the broken env is using `pillow` while the working env is using `tifffile`. I'm not sure where the code change is, but not at least we understand what the important difference is. I'll do the rest in person later if you guys can work from jupyterhub for now.

**Comment by danielballan** [comment]
Ah, got it. PIMS was falling back on scipy's `imread` instead of scikit-image's imread. Installing sckit-image on xf28id1-ws2 fixed the issue:

```
In [4]: !hostname
xf28id1-ws2

In [5]: get_images(db['4e1af641'], 'pe1_image_lightfield')[0].dtype
Out[5]: dtype('float32')
```

**Comment by pavoljuhas** [comment]
@danielballan Thank you, it works well now.  No more data squashing to 2 values.  :-)
