### ISSUE TITLE
LRU cache from python core

### ISSUE THREAD

**Issue by ericdill** [NSLS-II/filestore#69]
@tacaswell I just discovered that python 3 has a built in LRU cache. Is it possible to use this instead of the one from boltons?

**Comment by tacaswell** [comment]
This still has to support legacy python.

**Comment by ericdill** [comment]
Ah. Compelling reason.

**Comment by arkilic** [comment]
How about pyLRU which has 2.6+ and 3.x support?
https://pypi.python.org/pypi/pylru

**Comment by ericdill** [comment]
We might as well keep using boltons, instead of switching dependencies

**Comment by arkilic** [comment]
We have gotten rid off boltons (in mds) a while ago because it has some funky bugs

**Comment by ericdill** [comment]
Ah, I guess I missed that discussion about boltons bugs
