### ISSUE TITLE
ENH: Point filestore at various DBs

### ISSUE THREAD

**Issue by CJ-Wright** [NSLS-II/filestore#72]
It would be nice if we could separate various filestores.  Thus, other software can use filestore without interfering with other filestore DBs.  To facilitate this we should move filestore configuration to an object which knows where the database associated with it is.

**Comment by danielballan** [comment]
:100:

@tacaswell and I have discussed that "configuring" filestore/metadatastore on import was a bad call (though no one was saying so at the time). Obviously *users* don't want to be dealing with setting of database connections, but the databroker could handle this just fine.

**Comment by CJ-Wright** [comment]
I can't take much credit @tacaswell and I were also discussing it.  I just wanted an issue to work against if I got the chance to work on it.

**Comment by CJ-Wright** [comment]
I think that this has been solved by moving to a databroker that takes MDS and FS as args. Just make a new FS instance and plug it into a DB and your good to go.
