### ISSUE TITLE
Re-visit resource index creation

### ISSUE THREAD

**Issue by klauer** [NSLS-II/filestore#81]
PR #80 didn't quite do it for reasons that are beyond me. For reference, doing this on an interactive session fixed HXN's massive db in a matter of minutes:

``` python
import filestore.api

fstore = filestore.api._FS_SINGLETON
collection = fstore._db.datum
collection.create_index('resource')
```

Retrievals are down from 30 sec to 0.025 sec!

**Comment by danielballan** [comment]
attn @licode Any idea if this index is still in place?

**Comment by licode** [comment]
'resource' is used in datum. So far so good. There was a hot fix at hxn on this at the beginning of this cycle.  https://github.com/NSLS-II-HXN/hxntools/pull/9/files

**Comment by danielballan** [comment]
I could be confused but that I don't think that issue is at all related to this one, which is about mongo indices.
