### ISSUE TITLE
Add support for updating links to moved files

### ISSUE THREAD

**Issue by klauer** [NSLS-II/filestore#88]
And/or a facility to move files and then update the filestore links in one step.

This has been talked about for a while, but I'd like to bump its priority level. 
HXN is having some storage-related issues, and as such I'd like to retroactively reorganize 2d pixel array detector files.

... they'll need this in the very near future.

**Comment by tacaswell** [comment]
:scream: 

Unless something else comes up I will plan to sink time in to this this week.

Can you comment on https://github.com/NSLS-II/filestore/pull/58 ?

**Comment by heroux** [comment]
Great! I will lean on Robert to try to get acces to the centralized storage

**Comment by klauer** [comment]
@tacaswell I think #58 is a good long-term solution, but perhaps in the short-term a simple move/update entry utility would be preferable. I'd rather not have backward-compatibility breaking changes while being held back on some other versions.

**Comment by danielballan** [comment]
Done.
