### ISSUE TITLE
Fix retrieve/get_datum/get_data in refactor

### ISSUE THREAD

**Issue by danielballan** [NSLS-II/filestore#89]
@tacaswell There is no `FileStore.retrieve`. Shouldn't there be? There is `FileStore.get_datum`, but it does not accept the same arguments that `retrieve` did/does.

Also, what is the difference between a handle_registry and a handler_registry?

**Comment by danielballan** [comment]
FYI, this came up in the context of finishing the DataBroker refactor.

**Comment by tacaswell** [comment]
The way I imagine using `get_datum` is via the context manager

```python
with FS.handler_context(tmp_reg) as fs:
    fs.get_datum(eid)
```

handle vs handler is a typo.

**Comment by danielballan** [comment]
I fixed this at some point and forgot to close the issue.
